version: "3.8"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  node0:
    container_name: charon_node0
    image: docker.pkg.github.com/obolnetwork/charon/charon:97d766ed
    hostname: charon
    command: charon run --data-dir="./charon-simnet/node0" --manifest-file="./charon-simnet/manifest.json" --monitoring-address="127.0.0.1:15003" --validator-api-address="127.0.0.1:15004" --p2p-tcp-address=127.0.0.1:15001 --p2p-udp-address=127.0.0.1:15002
    user: root
    volumes:
      - ./charon-simnet:/charon-simnet
    ports:
      - 15001:15001/tcp
      - 15002:15002/udp
    <<: *logging

  node1:
    container_name: charon_node1
    image: docker.pkg.github.com/obolnetwork/charon/charon:97d766ed
    hostname: charon
    command: charon run --data-dir="./charon-simnet/node1" --manifest-file="./charon-simnet/manifest.json" --monitoring-address="127.0.0.1:15007" --validator-api-address="127.0.0.1:15008" --p2p-tcp-address=127.0.0.1:15005 --p2p-udp-address=127.0.0.1:15006
    user: root
    volumes:
      - ./charon-simnet:/charon-simnet
    ports:
      - 15005:15005/tcp
      - 15006:15006/udp
    <<: *logging

  node2:
    container_name: charon_node2
    image: docker.pkg.github.com/obolnetwork/charon/charon:97d766ed
    hostname: charon
    command: charon run --data-dir="./charon-simnet/node2" --manifest-file="./charon-simnet/manifest.json" --monitoring-address="127.0.0.1:15011" --validator-api-address="127.0.0.1:15012" --p2p-tcp-address=127.0.0.1:15009 --p2p-udp-address=127.0.0.1:15010
    user: root
    volumes:
      - ./charon-simnet:/charon-simnet
    ports:
      - 15009:15009/tcp
      - 15010:15010/udp
    <<: *logging

  node3:
    container_name: charon_node3
    image: docker.pkg.github.com/obolnetwork/charon/charon:97d766ed
    hostname: charon
    command: charon run --data-dir="./charon-simnet/node3" --manifest-file="./charon-simnet/manifest.json" --monitoring-address="127.0.0.1:15015" --validator-api-address="127.0.0.1:15016" --p2p-tcp-address=127.0.0.1:15013 --p2p-udp-address=127.0.0.1:15014
    user: root
    volumes:
      - ./charon-simnet:/charon-simnet
    ports:
      - 15013:15013/tcp
      - 15014:15014/udp
    <<: *logging